
services:
  api:
    build: ./app
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./app/bdk:/code/app/bdk
  
  api2:
    build: ./app2
    container_name: api2
    ports:
      - "8082:8000"

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file:
      - ./.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    ports:
      - '8081:8081'